### PR TITLE
chore: fix build

### PR DESCRIPTION
**Pull request by alangpierce**
There was a rollup error on travis that looks like it may have been due to
cached old dependencies; things worked locally for me. So update package.json to
explicitly specify those dependencies to bust the cache.

Also, there's now a new `identifierName` field in the babylon AST, so update all
tests to include those in the expected output.

### CODE REVIEW

**Comment by alangpierce** [comment]
Drat, I was hoping that would work. I'll try other things...

**Comment by alangpierce** [comment]
Looks like I was on npm 3 and the failure was only on npm 2. Just pushed another commit that hopefully fixes things.

**Comment by alangpierce** [comment]
@eventualbuddha FYI I have a bunch of decaffeinate fixes (list below) that need esnext changes, so they're blocked on this. I'll wait until this one is merged before submitting the PRs since I don't want the builds to all fail.

https://github.com/decaffeinate/decaffeinate/issues/404
https://github.com/decaffeinate/decaffeinate/issues/516
https://github.com/decaffeinate/decaffeinate/issues/500
https://github.com/decaffeinate/decaffeinate/issues/527
https://github.com/decaffeinate/decaffeinate/issues/506

**Comment by eventualbuddha** [comment]
Merged. Thanks!

**Pull request merged**
